silverbulletmd/silverbullet

packages/web/components/panel.tsx

Arguments were not passed correctly and were wrapped in an array.
props to @zefhemel as he pointed the error, this is just the fix so he doesn't have to remember ;)

fix argument passing

---

README.md

another link needed updating after docs move

Fix docs/website link

---

packages/plugs/core/page.ts

Relevant issue: https://github.com/silverbulletmd/silverbullet/issues/49

Fix deletion of page on renaming to current name

---

website/🔌 Query.md

This PR updates the document for `query` and usage of `data objects` with examples
Fixes: https://github.com/silverbulletmd/silverbullet/issues/40
Fixes: https://github.com/silverbulletmd/silverbullet/issues/43

Write documentation for Query and Data

---

website/🔌 Query.md

This PR
- enhance Query section by adding available operators
- creates a new section to further explain the usage of templates
Fixes https://github.com/silverbulletmd/silverbullet/issues/55

Add operators for Query section and create Templates section 

---

.github/workflows/docker.yml
.github/workflows/test.yml
Dockerfile
README.md
docker-compose.yaml
scripts/build_docker.sh
web/cm_plugins/wiki_link.ts
website/CHANGELOG.md

As discussed in #150 using the work done by @brtwrst @MaverickDe and @BaptisteBdn

Deno docker update

---

web/components/command_palette.tsx
web/components/filter.tsx
web/components/top_bar.tsx
web/deps.ts
web/editor.tsx
web/styles/filter_box.scss
web/styles/theme.scss
website/CHANGELOG.md
website/Silver Bullet.md

Switch to feather icons

---

cmd/upgrade.ts

Improve upgrade message:
- Fix CHANGELOG link
- A few nitpicky grammar fixes

Improve upgrade message

---

website/🔌 Plugs.md

Changed the word 'specific'
Hopefully I'm doing this right. It's my first time :)

Fix typo on plugs.md

---

website/🔌 Core/Templates.md

From the changelog it seems like this setting was added in 0.0.31 but doesn't appear to be documented anywhere. 
Thanks for this project! Let me know if you have any feedback, and/or if you'd like me to keep submitting PRs like these when I find them.

update daily note documentation

---

web/components/filter.tsx
web/components/mini_editor.tsx

As described in https://github.com/silverbulletmd/silverbullet/issues/230
I tried routing keydown via CodeMIrror / MiniEditor like keyup but couldn't figure it out.
Instead I hooked global keydown.

better up / down handling in FilterList

---

website/🔌 Directive/Query.md

clarify documentation that the data sources are space wide, not just for the page where the query lives.

Update Query.md documentation 

---

website/🔌 Directive/Query.md

The closest page to what I think this used to reference is https://github.com/silverbulletmd/silverbullet/blob/d609daf59ecf5855d0688ceb8f2a10e9f21a14d0/plug-api/lib/query.ts and I'm not sure if that provides much value in terms of understanding any of the query grammar.

Update Query.md documentation broken link

---

website/Silver Bullet.md

When I read this initially, I thought 0.0.0.0 was a placeholder, not an actual suggestion. Might be able to be worded a bit different, perhaps a breakout section on each flag option? 
Context: #278

Update Silver Bullet.md with more hostname documentation

---

common/deps.ts
web/editor.tsx

As discussed in https://github.com/silverbulletmd/silverbullet/issues/234.

Adds support for SQL language syntax highlighting.

---

website/🔌 Markdown.md

Update 🔌 Markdown.md

---

common/manifest.ts
common/spaces/sync.test.ts
common/spaces/sync.ts
common/syscalls/sync.ts
deno.jsonc
import_map.json
mobile/boot.ts
mobile/deps.ts
mobile/package-lock.json
mobile/package.json
plug-api/silverbullet-syscall/sync.ts
plugos/hooks/cron.ts
plugs/sync/sync.plug.yaml
plugs/sync/sync.ts
server/space_system.ts
website/CHANGELOG.md
website/Sync.md

Continuous sync

---

README.md

Add how to run type checker and unit tests while developing SB

[easy] README: running typechecker and unit tests

---

website/STYLES.md

Add more css customization examples

Add more customization examples to STYLES.md

---

.github/workflows/docker.yml
Dockerfile

Hello,
this pull-request targets:
- Fixes: https://github.com/silverbulletmd/silverbullet/issues/136
- Extends: https://github.com/silverbulletmd/silverbullet/issues/198
Additionally it also pushes to the github container registry (GHCR.io)
An Example registry deployment can get found for the imaginary next release:
- https://github.com/sweisgerber/silverbullet/releases/tag/0.2.14
- DockerHub: https://hub.docker.com/layers/sweisgerber/silverbullet/0.2.14/images/sha256-81ec535cb4b71a01623f15aa93587af6ef6639254478d91f794d986bc829fc3f?context=explore
- ghcr.io: https://github.com/sweisgerber/silverbullet/pkgs/container/silverbullet/91495509?tag=0.2.14
If desired I can rollback pushing to ghcr or add more tags (e.g. for branches).

Feature: Docker multiarch image (amd64 & arm64) dynamic tags and ghcr repositoy

---

Dockerfile

- Fixing permissions for /deno-dir as well
Issue: #402

Added silverbullet user with 1000:1000 IDs, runnign deno as this user

---

website/Deployments.md

I created a deployments doc to provide a couple of examples on:
- How to deploy SB within docker and with caddy,redis and authelia
- How to deploy SB with Deno and set up a service to run it at boot time

SilverBullet deployments examples

---

plugs/search/engine.ts

Add page names to search index

---

plugs/directive/directives.ts

Quick addition to add a little context to directive error messages. Helps find the problem on a page with a lot of them.

Add filename and directive content to directive error messages

---

website/Admonitions.md

Create Admonitions.md
This is already mentioned in the `CHANGELOG.md`, but I think it is easier to find when it has a seperate page.

Add docs for admonitions

---

website/Anchors.md

Update typo in Anchors.md

---

plug-api/silverbullet-syscall/editor.ts
plug-api/types.ts
web/syscalls/editor.ts

This is more a base for discussion.
Not quite sure about any of this.
All I can say that this together with https://github.com/prcrst/silverbullet-attach works and that it is less hacky than the last solution I made :)

Implement editor.uploadFile syscall

---

plug-api/types.ts
plugs/editor/editor.plug.yaml
plugs/editor/upload.ts
web/syscalls/editor.ts

It works, I'd like to get rid of some of the copy/pasted code

Upload file command with copy/paste logic

---

website/Install/Docker.md

remove the quotes which cause "Invalid username or password" https://github.com/silverbulletmd/silverbullet/issues/609

Update docs Install/Docker.md

---

common/deps.ts
common/languages.ts

Adds go language support for code blocks.
Great project but this is the thing that currently keeps me from using silverbullet 😃

Add go code block support

---

Dockerfile

This implements #722.
Tested build and produced image locally. All good.

Switch to official deno image

---

common/settings.test.ts
common/settings.ts
plugs/query/complete.ts
web/client.ts
web/cm_plugins/fenced_code.ts

This seems to fix #693
*Yes, it did take me longer to write the report than the PR, no it is not funny.*

Change fenced code regex to include tildes

---

web/components/top_bar.tsx
web/styles/main.scss

With alignment regression fixed

Change top bar to flexbox (take 2)

---

web/cm_plugins/admonition.ts

Fix admonitions without style

---

web/styles/colors.scss
web/styles/theme.scss

fix completion colors

---

plugs/editor/upload.ts
web/cm_plugins/editor_paste.ts
web/constants.ts

following #832 was not handling drag and drop of files.

Configurable upload file size for drag and drop too

---

cmd/server.ts
website/Install/Configuration.md

@zefhemel hey, here is my simplistic implementation of customizable `manifest.json`. What do you think? 
If you like it I will update documentation and cli usage message too.

Provide a way to customize app name & desc

---

website/Install/Deno Deploy.md

According to https://community.silverbullet.md/t/deploy-to-deno-deploy, the entrypoint has changed.

docs: update deno deploy entrypoint url

---

web/manifest.json
web/styles/main.scss

Based on this article: https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/window-controls-overlay
Some minor eye-candy.

Window controls overlay

---

common/markdown_parser/customtags.ts
common/markdown_parser/parser.ts
plugs/editor/navigate.ts
plugs/markdown/markdown_render.ts
server/http_server.ts
web/cm_plugins/block.ts
web/cm_plugins/inline_image.ts

Support size for images

---

plug-api/README.md
plug-api/syscalls/editor.ts
plugs/editor/editor.plug.yaml
plugs/editor/editor.ts
web/syscalls/editor.ts

Delete line command

---

common/languages.ts

Added erlang support

---

plugs/markdown/preview.ts
web/components/panel.tsx
web/components/panel_html.ts
web/styles/main.scss
web/styles/theme.scss

This fixes #865
I actually went kind of insane fixing this lol. FYI `iframe`s exert [weird behaviour](https://fvsch.com/transparent-iframes) when using different `color-scheme`s

Fix for flashing markdown preview

---

website/Library/Core/Snippet/include-note.md
website/Library/Core/Snippet/include-page.md

I think that this could be a useful default template for people to include previews of other (markdown files). Such as is done in the intro/tutorial (Getting started) file.

Include a preview of another note

---

web/cm_plugins/smart_quotes.ts

Added automatic quote insertion

---

web/cm_plugins/clean.ts
web/cm_plugins/escapes.ts

Basically just hides the slash from escaped characters unless the text is selected

Hides the '\' from escaped characters

---

web/index.html

chore: Update index.html to include no referrer

---

common/spaces/http_space_primitives.ts

Added a 5 second timeout on fetch request. Fixes #947

Added a timeout for fetch

---

web/styles/editor.scss

Unified the size of headers and sb-line-headers

---

website/Page Decorations.md

added missing "attributes" to the sample yaml provided.

Update Page Decorations.md

---

web/cm_plugins/inline_content.ts
web/editor_state.ts
web/styles/editor.scss
website/Attachments.md
website/Transclusions.md

Embed video, audio and pdf

---

website/Install/Docker.md

Fixed a typo in a command in Install/Docker.md.

Fix documentations.

---

common/languages.ts
deno.json

Uses https://github.com/replit/codemirror-lang-nix

Add nix language syntax highlighting

---

website/Install/Configuration.md

Fixes https://github.com/silverbulletmd/silverbullet/issues/1092

Add tips for slow drives

---

plugs/tasks/task.ts

Convert bullet to task when Task: Cycle State is called

---

website/Library/Core/Widget/Linked Tasks.md

Fixes https://github.com/silverbulletmd/silverbullet/issues/1119

Linked Tasks: Include tasks linked to aliases

---

plugs/index/tag_page.ts

Fix rendering on tag pages

---

README.md
website/Development.md

Hi
Oak was replaced by Hono in commit 291280b
Thanks

doc: replace Oak mentions by Hono

---

common/languages.ts
website/Markdown/Syntax Highlighting.md

Fixed swift syntax highlighting and updated example in website as well.

Fix Swift syntax highlighting

---

website/Library/Core/Page/Maintenance.md
website/Spaces.md

Just wanted to fix a few small spelling or grammar mistakes that I noticed in the website!

Spelling and grammar corrections to website

---

web/client.ts
web/syscalls/editor.ts

Remove `editor.setText` syscall from client

---

web/client.ts
web/editor_state.ts

fix(editorState): Reset undo history after editor init

---

web/document_editor.ts

Tiny fix, otherwise some funky stuff could happen when saving

Update `currentPath` on file change

---

common/markdown_parser/parser.test.ts
common/markdown_parser/table_parser.ts
plugs/template/util.ts

- Fixes #943
- Fixes #1016 
The transformer used to escape any pipe (`|`), which lead to incorrect links (#943) and broken command buttons.
To fix the command buttons (#1016), the check to see if we are inside the command-syntax was added in a similar way as the check of the wiki-links.

fix(tables): only escape pipes outside SB context

---

server/http_server.ts

Uses the hono api correctly

---

server/http_server.ts
web/client.ts
web/document_editor_skeleton.ts

Some more fixes for document editors, best described in the commit messages

A few fixes for document editors

---

Library/Std/Widgets.md

https://github.com/silverbulletmd/silverbullet/issues/1349

Add priority to linked mentions and tasks templates

---

web/auth.html

This pull request updates the `auth.html` file to dynamically fetch and display the application name from the manifest file.

Dynamic App Name Loading for Auth Page

---

Library/Std/Config.md
website/Frontmatter.md
website/Space Lua/Lua Integrated Query.md

- Add another line to Frontmatter which shows that page references should be quoted
- [Handling of database-like structures + links in frontmatter](https://community.silverbullet.md/t/handling-of-database-like-structures-links-in-frontmatter/2262)
- Mention feather icons in actionButtons documentation
- [List of all icons](https://community.silverbullet.md/t/list-of-all-icons/2256)
- Add an example of filtering based on name,with link to string API
- [V2 - Understanding queries lua and help to migrate old requests](https://community.silverbullet.md/t/v2-understanding-queries-lua-and-help-to-migrate-old-requests/2253)
- [How can I view all my Quick Notes (the inbox?)](https://community.silverbullet.md/chat/c/-/2/1712)

Mention answers to recent forum questions on website

---

common/space_lua/stdlib/string.ts
common/space_lua/stdlib/string_test.lua

Escape pipe symbol in string.gsub

---

common/space_lua/stdlib/os.ts
common/space_lua/stdlib/os_test.lua

Fix week calculation

---

common/space_lua/stdlib/math.ts

* add missing case `math.random(0)` which produces an integer with all bits (pseudo)random
* check arguments and throw `LuaRuntimeError` for invalid input

Add missing case to math.random and check arguments

---

Library/Std/Query Templates.md
Library/Std/Tag.md

Fix paragraphs for the tag page

---

.github/workflows/docker.yml
.github/workflows/release.yml
.github/workflows/server.yml
.github/workflows/test.yml

This fetches tags and history to enable proper version string generation using git describe, as introduced in #1374.

Fetch tags and history for proper version string generation

---

web/editor_state.ts

Fixes https://github.com/silverbulletmd/silverbullet/issues/1350

Fix support for disabling shortcuts

---

Library/Std/Pages/Maintenance.md

While testing this nice application I found an error in the Maintenance page, a closing bracket was missing

fix: closing bracket is missing

---

plug-api/syscalls/markdown.ts
website/API/markdown.md

Adds missing doc for syscalls

---

lib/space_lua/stdlib/os.ts
lib/space_lua/stdlib/os_test.lua

Fix os.time

---

web/hooks/event.ts

Only noticed now, overlooked that functions have a default return. This should fix stuff like `tag:` pages not working anymore.
Before, sometimes it was deliberately compared to undefined and sometimes we checked if it's falsy. I now opted to only filter null and undefined, I think this is reasonable.

Filter nullish values from dispatch

---

web/hooks/event.ts

Fix event dispatch

---

website/Space Lua.md

To be more obvious I restructured the documentation in form of tables. (Also fixed some minor typos.)

Improve documentation of string to number conversion
