silverbulletmd/silverbullet

packages/plugs/core/core.plug.yaml
packages/plugs/core/text.ts

Add links with cmd/ctrl+shift+k (feel free to change it afterwards)
It tries to detect if the selected text should be wrapped as url or as display text. If no text is selected, then it adds an empty link.
Future improvements: 
- better/flexible url detection (right now it requires having a protocol)
- maybe use a modal as other tools do that show the display text and the url and allows for editing
- ~~move caret to first empty section.~~ Done

Add link command

---

README.md

The `docs` folder is now named `website`.

Docs: Fix folder reference

---

packages/plugs/core/core.plug.yaml
packages/plugs/core/plugmanager.ts
website/🔌 Plugs.md

After writing the discussion on https://github.com/silverbulletmd/silverbullet/discussions/47
I figured at least the protocol should be easy to do and here it is. I modified the backlinks release to conform to that one so once this is merged you can install silverbullet-backlinks by adding:
```yaml
- ghr:willyfrog/silverbullet-backlinks
```
or specify a version
```yaml
- ghr:willyfrog/silverbullet-backlinks/v0.2
```
I haven't properly managed what happens on unresolved plugs, as I think it is out of scope. Right now it is throwing an error the same way an unresolved https plug does
This is it in action
.

Add GHR protocol to plug manager

---

packages/plugs/core/plugmanager.ts

So I inadvertently added a space, which is valid YAML but not the one expected.
this should give a more meaningful message, I still think we need a better way to notify users, but for now this works.

Improve error on formating plug sections

---

packages/web/components/filter.tsx

Since I typically have my browsers full-screened in macOS if the default action of `Escape` is _not_ `e.preventDefault()`-ed then I get the behavior of the browser window itself exiting full screen. This fixes that.

fix: `Esc` prevent default (browser) action

---

packages/web/components/top_bar.tsx
packages/web/editor.tsx
packages/web/index.html
packages/web/styles/main.scss
packages/web/styles/theme.scss

This probably closes #2.
Spent a bit more time tweaking the styling and then decided to go forward with persisting it via `localStorage` and a `data-theme` on the root `<html>` element. I was particularly thinking if using the app on a mobile device or via a PWA install then toggling the browser's `prefers-color-scheme` is probably less ideal.
I did end up fighting Parcel's service worker cache version key where it kept serving a cached copy of the index.html on page reloads. Restarting the watch script seemed to fix that.
I think this a good first-pass effort:
- the SCSS could probably be refactored into common variables, etc
- since the majority of SB presents as a fancy text editor, I'm curious if it's trivial or not to swap out the theme for just _that_ e.g. I'm a personal fan of …

feat: dark theme

---

packages/web/components/top_bar.tsx

Add a hint about the keybord shortcut to the command switcher icon. Otherwise there is no way to discover it in the product.

Add shortcut hint for command switcher

---

.gitpod.yml
README.md

This PR add support for running SB in a Gitpod. It's tarting developers who want to work in a cloud workspace. For a demo netlify is better used.
The dev environment is setup in the same way as as suggested in the [readme](https://github.com/silverbulletmd/silverbullet#developing-silver-bullet). Hence, all changes are automatically picked up. (Expect for changes to pugs).
The `npm` version used in Gitpod is the one defined in  `.nvmrc`.
Please note that in order for [prebuilds](https://www.gitpod.io/docs/prebuilds) to work the [Gitpod GitHub app](https://github.com/apps/gitpod-io) needs to be added to this repository: https://www.gitpod.io/docs/prebuilds#configuring-prebuilds-manually.
Fixes https://github.com/silverbulletmd/silverbullet/issues/77

Add Gitpod support

---

.gitpod.Dockerfile
.gitpod.yml

When a Gitpod was restarted or started from a prebuilt the `init` command are not run again. This resulted in `nvm use` not being run and a node version mismatch happening.
To avoid this issue a custom Dockerimage is used. This has the unfortunate effect that the node version is not synced with `.nvmrc`.

Fix prebuilt image

---

packages/plugs/core/dates.ts
packages/plugs/core/template.ts

`toISOString()` returns the time in UTC. This leads to e.g. `{[Open Daily Note]} ` ignoring the timezone of the user. `/today` was also affected.
`niceDate()` now renders it's string without the use of `toISOString()`.
Fixes https://github.com/silverbulletmd/silverbullet/issues/83

Ensure dates consider timezones

---

README.md
cmd/server.ts
server/http_server.ts
silverbullet.ts
website/Silver Bullet.md

I suggested this in https://github.com/silverbulletmd/silverbullet/issues/16#issuecomment-1336213572

Allow the user to specify hostname to listen on

---

website/🔌 Backlinks.md

Fixes incorrect URL for the plug in its README.
Original:
` https://github.com/Willyfrog/silverbullet-backlinks/releases/download/v0.3/backlinks.plug.json`
Fixed:
`https://github.com/Willyfrog/silverbullet-backlinks/releases/download/v0.3/silverbullet-backlinks.plug.json`

Update backlinks plug JSON URL.

---

web/cm_plugins/admonition.ts
web/cm_plugins/clean.ts
web/styles/editor.scss
web/styles/theme.scss

Resolves #67
Adds initial markdown support for Admonitions (using github syntax):
```
> **note** Note Admonition
> This is a Note Admonition
```
And:
```
> **warning** Warning Admonition
> This is a Warning Admonition
```

Initial Admonition support (github format)

---

plugs/core/core.plug.yaml
plugs/core/page.ts
web/editor.tsx

Renaming a page works when pressing <kbd>Enter</kbd> after editing the page name, but fails when using the "Rename page" command, either from the command palette for via hotkey (Cmd+Alt+R):
The `renamePage` function expects a string but is called with a command definition (`cmdDef`). This probably deserves a refactor, but overloading the command definition with a `page` parameter allows it to be called successfully in both contexts.

Fix "Rename page" command

---

docker-compose.yaml

I propose to change the "command" hint in docker compose to a list element.
This way:
- style is aligned to docker file
- users are allowed to just uncomment and insert desired user:pwd values to enable BasicAuth

Minor change in docker compose to BasicAuth

---

build_plugs.ts
deno.jsonc
plugos/deps.ts

Fix `deno task build` for Windows.
Windows doesn't support `.sh` files so replaced with direct usage in `deno.jsonc`.
Since we're no longer going via shell, the glob patterns are not expanded so modified `plugos-bundle.ts` to assume that if no files are given, we want to build everything and we glob ourselves.
Alternative: still pass glob pattern on cmd-line and glob internally (will be no-op if already globbed).
`build_plugs.sh` is no longer used but I left it in case you're using it from cmd-line.
Makes progress on #107

deno task build fixes for windows

---

website/🔌 Directive/Query.md

Add in a description of hardcoded variables you can use in queries, seems pretty relevant for bullet journal style scripting of tasks. 
Since this is copied from core/templates, and likely to change(?) maybe it would be best to use an #include directive and break out into a separate file?
related: https://github.com/silverbulletmd/silverbullet/discussions/147

Update Query.md with information about "dynamic" query parameters. 

---

plugs/core/core.plug.yaml
plugs/core/refactor.ts

- `Refactor: Extract to new page` seems cumbersome, so I omitted the refactor. I'm not sure if the "category" is necessary for core plugins, but seems like a good idea for 3rd party. 
- mostly this is based on the existing plugs for renaming  (including the file overwrite protection) and text editing
- Happy to write some tests, but didn't see any infrastructure for it
- I don't know what `cmdDef.page` is doing, it seems like you can declare a argument in the yaml file, but I'm not sure how you would invoke it for page rename for example. Is that for use by other functions?

add in new refactor file and extract to page command; #210

---

plugs/core/core.plug.yaml
plugs/core/text.ts

I originally wanted to add in just the keyboard shortcut (cmd+shift+8 I think is by far the most common, google/slack etc.) but also fixed a bug /expanded scope that allows you to listify the current line that the cursor is in, not having to select text first. 
I think ideally listifying would be more like a toggle (subsequent invocations would de-listify) instead of the current behavior where you just add bullets with each invocation. 
As always, open to whatever feedback and discussion!

update listify command to work with selection and add keyboard shortcut

---

mobile/android/build.gradle
mobile/android/gradle/wrapper/gradle-wrapper.properties
mobile/android/variables.gradle
mobile/package-lock.json

This PR allows the app to be built with the latest version of Android Studio.
It fixes a dependency issue, so all that needs to be done is `./gradlew
assemble` (or run it from android studio)
* Update the SDK compile version to 33 to fix dependency issues
* Update the Build plugin as a dependency

Update Android build

---

plug-api/lib/query.ts
plugs/directive/parser.ts
plugs/directive/query.test.ts

Fixes #385 
* The grammar already supports multiple `order by` clauses
* Modified `ParsedQuery` to be able to contain multiple `order by` clauses by adding `ordering: QueryOrdering[]`
* Added the logic to do sorting by multiple keys
* Invariant: The behavior on single key sort is kept as before.
An Interesting bug that surfaced: When comparing tags, which are array, in earlier implementation the comparison always resulted in a "===" being false even when tags were equal. This automatically resulted in `a` being greater than `b`. For a single key it didn't matter. But kf we keep that implementation as is (which first compares the a and b by an `===`) then that would mean that it will always return false on comparison which would mean that we will never evaluate the latter keys.

Add support for multiple order by

---

web/styles/theme.scss

Hi @zefhemel :)
Silverbullet is an awesome app that I thoroughly enjoy. Thanks for creating it! In fact, I even tried to build [something similar](https://github.com/jim-fx/notarium) myself.
Among the many features of Silverbullet, I particularly enjoy using the vim-mode and dark theme. However, I believe there is still some room for improvement to the readable of the dark theme.
Changes:
- switched dark mode background from `#000` to `#111`
- Made the vim status bar the same width as the content window
- made the vim selection a bit transparent so text is readable when selected
- made the top-bar and the vim-status bar the same background color
- increased the contrast of the query header so it is readable
- make the "frontmatter" text readable 
Edit: I just saw that there are some open …

feat: make darkmode more readable

---

server/http_server.ts
website/Server.md
website/Sync.md

Allow BasicAuth credentials to be specified with the `SB_USER` environment variable. This prevents the password from being revealed when listing processes with the ps command.

Accept SB_USER environment variable as a secondary source of creds

---

plugs/tasks/task.ts

Create new postponed date as a "naive" date to prevent it from being converted to UTC.

Fix date calculation in `Task: Postpone` command

---

.gitignore
web/components/top_bar.tsx
web/editor.tsx

I often want to be able to middle click to open the space's home page in a separate tab. The current code for top bar action buttons doesn't allow for this browser built in functionality. The changes in this PR are to allow action buttons to optionally be contained in an anchor tag with an href. This PR also applies that functionality to the home button.

allow top bar action buttons to be links and make home one

---

web/editor.tsx

This patch calls event.preventDefault() in touch start/end event handlers so that mouse events won't be fired as well. The most notable issue this fixes is links opening multiple times on mobile.

Prevent duplicate tap events

---

README.md

Fix link in README.md from `https://silverbullet.md/🔌_Plugs` to `https://silverbullet.md/🔌%20Plugs`

Fix link to plugs in `README.md`

---

web/index.html
web/styles/colors.scss
web/styles/editor.scss
web/styles/main.scss
web/styles/modals.scss
web/styles/theme.scss

This pull request organizes and cleans up the scss files in preparation for css variable based theming (as proposed in https://github.com/silverbulletmd/silverbullet/discussions/58 and https://github.com/silverbulletmd/silverbullet/issues/127)
At the moment i just refactored the existing theme to use css variables and am quite sure not everything has a variable yet.
Also the customStyles should need less `!important` markers, as i moved the style tag below the main.css.
My idea going forward is the following:
1. create a css variable for almost everything. Make it quite verbose, so you can color your editor to look lika a rainbow if you wanted to.
2. Create a basic palette of colors which are assigned to all these verbose variables, but summarize common colors (like all subtle colors will …

Refactor SCSS to use CSS variables

---

web/editor.tsx

By default, codemirror would only scroll enough to get the cursor on screen when navigating to a new page position.
This can be disorienting, especially when navigating to anchors like on the [directives](https://silverbullet.md/%F0%9F%94%8C%20Directive) page.

Move Viewport Top to Cursor on page navigate.

---

common/manifest.ts
plugos/types.ts

Just a little documentation for manifest type definition. Hoping to add this to copy most of this info to the website at some point. But I thought putting it in code would be a good place to start.

Add inline manifest documentation

---

plugs/index/builtins.ts
plugs/index/index.plug.yaml
plugs/index/paragraph.ts

Only considers top level paragraphs (right below Document node).
Includes attributes and tags in the paragraphs.
Just something I threw together real quick after seeing the discussion on discord. Definitely needs more tests.

Index plug: index paragraph nodes

---

plugs/query/assets/style.css

Love the new query stuff!
There were some slight issues with readability on dark mode, so I made this PR.
- Moves the button bar right into the corner
- Make the background of the button bar a bit more consistent with the rest of the ui and more readable in dark mode
- Adds some slight padding to the left side of the results (10px)

style queries a bit nicer :)

---

common/syscalls/handlebar_helpers.ts
plug-api/lib/dates.ts
plugs/template/template.ts

I was looking to create an "interstitial journal" timestamp snippet, and found there was no {time} helper. I centralised the code from the Quick Note alongside niceDate.
This should yield hh:mm:ss (although I'd personally prefer hh:mm), bear in mind this is my first time writing TypeScript :)

Add a {time} template helper, reuse timestamp code from Quick Note as a niceTime

---

website/Guide/Deployment/Cloudflare and Portainer.md

The user inside the container (defined by PUID and PGID environment variables) needs to have write access to this directory. Otherwise, the silverbullet would run in an error state:
*attempt to write a readonly database: Error code 8: Attempt to write a readonly database*

docs: update deployment guide for cloudflared

---

.vscode/settings.json
plugs/emoji/emoji.ts
web/types.ts
website/Plugs/Emoji.md
website/SETTINGS.md

Allows users to define emoji aliases in SETTINGS which are then used in hints after `:`. Some details we might want to discuss:
The settings are `emoji: aliases:`, instead of `emojiAliases:`, it feels a bit weird to require double indent, but it's putting everything under the plug's name (as hinted here https://github.com/silverbulletmd/silverbullet/issues/226#issuecomment-1362014066). And getting an existing emoji list would have its own key for URL 🤔 
If I understood correctly, the complete handler would be run on each keystroke, so the config is updated in the background, with an interval [like federation config](https://github.com/silverbulletmd/silverbullet/blob/04abc283b065fd5666bbe33b67206ef816303bfc/plugs/federation/config.ts#L12-L14)

Plug: Emoji aliases (#246)

---

plug-api/silverbullet-syscall/editor.ts
plugs/editor/editor.plug.yaml
plugs/editor/navigate.ts
web/components/top_bar.tsx
web/editor_ui.tsx
web/reducer.ts
web/syscalls/editor.ts
web/types.ts
website/SETTINGS.md

This is my idea for solving #214 using `actionButtons` without cluttering the desktop client (also relevant for #639).
I was considering implementing some history internal to SilverBullet, but this seemed both overkill and wouldn't work with external links nicely. So I added a syscall for the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History). Conveniently, both `back()` and `forward()` are equivalent to `go(-1)` and `go(1)`.
I tested that mobile detection works on my Chrome and Firefox, Do we need to check browser compatibility more, since it's just an opt-in minor convenience?

Improve mobile navigation through history

---

web/styles/theme.scss

Change directive color in dark mode
Fixes https://github.com/silverbulletmd/silverbullet/issues/683
Screenshots:
|  before  |  after  |
|----|----|
|<img width="865" alt="Screenshot 2024-02-12 at 8 42 48 PM" src="https://github.com/silverbulletmd/silverbullet/assets/16203333/5b384ead-a6c3-4a25-8a74-149991fd3234"> | <img width="955" alt="Screenshot 2024-02-12 at 8 42 27 PM" src="https://github.com/silverbulletmd/silverbullet/assets/16203333/eb410b76-be4f-4bbd-9d0d-3957b9704276"> |

GH-683: Fix template dark mode

---

website/Client Modes.md
website/Install/Docker.md

I just spent time trying out SilverBullet by just running the Docker container without any reverse proxy or anything in front of it. I couldn't understand why the offline mode didn't work. Finally I found the output in the dev console explaining that the web worker didn't launch because I didn't use https. To avoid other people wasting time, I added a note about this in the docs for Synced mode and the Docker.md page.

Add note about https requirements

---

plugs/index/refactor.ts

Adds the ability to send additional arguments to `renamePageCommand` and `renamePrefixCommand` of the `index` plug, as well as returning `true` or `false` from each command to indicate whether the action was successful.
The arguments are completely optional, and the existing behavior remains the default when the additional arguments aren't provided, so everything remains fully backward-compatible. 
I've created a [tree view component/plug](https://github.com/joekrill/silverbullet-treeview) and one of the desired features is to [allow dragging and dropping nodes to rename pages](https://github.com/silverbulletmd/silverbullet/issues/102#issuecomment-1696908355). That renaming functionality already exists via these two methods, but we need to be able to pass in some values that are currently …

Allow passing additional arguments to `renamePageCommand` and `renamePrefixCommand`

---

common/syscalls/system.ts
plug-api/syscalls/system.ts

Adds a `syscall` -- `system.getVersion` -- for obtaining the current system version. Useful if plug functionality requires a minimum version to work.

Adds a `system.getVersion` syscall that returns the current system version

---

plugs/editor/editor.plug.yaml

The "Link: Unfurl" command always fails because it uses fetch to get the title of the patch, but the plug does not have `fetch` permission.

Add `fetch` to editor plug's `requiredPermissions`

---

web/syscalls/editor.ts

It looks like dispatching the `show-palette` action via a syscall doesn't include the current context. This means context-specific commands (like "Task: Postpone" and "Link: Unfurl") are not available even in the correct context.
Incidentally, the context _is_ correctly passed when [opening the command palette using three-finger tap](https://github.com/silverbulletmd/silverbullet/blob/cf010b5ef29a1dfde166241ae6e6c6dac21d89bf/web/editor_ui.tsx#L60).
Fixes #684

Include `context` when opening the command palette via syscall

---

web/editor_state.ts

A small bug was causing existing shortcuts to continue to work even when adding overrides to `SETTINGS` (the overrides worked as well).
Fixes #688
(Note this does _not_ fix #689 - looks like that's caused by something different)
@zefhemel I hope you don't mind me putting up these PRs! I thought I could help fix some of these small bugs.

Correctly skip adding default shortcuts for overriden commands

---

type/web.ts
web/client.ts

Stores the results of loading/parsing `settings.customStyles` in`uiOptions`.
For the [treeview plug](https://github.com/joekrill/silverbullet-treeview) I'd like to match the main application styles as closely as possible to be consistent. For the best results, we really need to:
1. Use the CSS variables and styles defined by the current theme. 
2. Know the current theme (dark mode).
3. Apply any user-defined custom styles.
The first two are fairly simple to handle in a plug (see [here](https://github.com/joekrill/silverbullet-treeview/blob/327d663ed52eb6aceb89dbf472d55c21b1f1ac46/treeview.ts#L104) and [here](https://github.com/joekrill/silverbullet-treeview/blob/327d663ed52eb6aceb89dbf472d55c21b1f1ac46/treeview.ts#L128)). In order to get the custom styles, though, I would have to …

Store extracted customStyles in uiOptions

---

web/cm_plugins/code_copy.ts
web/editor_state.ts
web/styles/editor.scss

For any code blocks - except `template`, `query`, and `embed` - adds a "Copy" button to the upper-right hand corner (next to the language string), which copies the raw text:
Implements #345

Add copy to clipboard button to code blocks

---

plugs/index/index.plug.yaml
plugs/index/table.ts
website/Objects.md

Adds support to query tables via the `table` object.
I'll do a little bit more polish the code later. However, the functionality is ready and seems to be working for all edge cases I tested.
This implements #725
I'd love to have a better and more intuitive value for the `table` property. But markdown doesn't support naming tables. Any ideas how we may name a table?

Add support for queryable markdown tables

---

plugs/template/page.ts

This PR adds the possibility to optionally use additional custom data to instantiate templates. 
The additional parameter can be used to inject additional data, so plugs or space-scripts can render data that was collected from external datasources.

Add custom data field to template plug

---

plugs/index/refactor.ts

Hi! 
Just started using silverbullet and find it to be fantastic. 
One small thing I've noticed: I often start with one page where I write stuff, using headings. When this page gets too long, I extract part of it, usually starting with a heading. And in most cases I want to name the page the exact same thing as the heading. So with this change, when extracting a page, it will check if the first line is a markdown heading. If it is, it will be used as a default name in the prompt asking for a page name.
This uses a regular expression to check for a heading. It seemed a bit overkill to do a full markdown parsing for this specific check.
JavaScript is far from my primary programming language, so please let me know if I'm doing something bad and I'll be happy to fix it!

Pre-fill new page name with heading

---

web/cm_plugins/code_copy.ts

This is a minor improvement to #735
I believe this to be a complete list now, because I looked at all markdown widgets with buttons in #719

Exclude copy code button from more code widgets

---

lib/data/mq.datastore.test.ts

Hello, awesome software :+1: !
I couldn't get the test to work no matter what I tried. Commit 687d1f0 helped, it made the test pass 9 times out of 10
This PR makes it work 10/10, but github loves to blow up when someone changes an indent so here's a rundown of what this PR does
- Replace `sleep`  with [FakeTime](https://docs.deno.com/runtime/manual/basics/testing/mocking#faking-time)
- Use try/finally to remove tmpFile and close the db even when a test fails
- Wait for the queue to be empty before running the 'subscribe' assert (see line 54)
If I may also suggest, [BDD testing](https://docs.deno.com/runtime/manual/basics/testing/behavior_driven_development) could be nice to better track and fix failing tests

Fix mq.datastore test

---

common/query_functions.test.ts
common/query_functions.ts
lib/builtin_query_functions.test.ts
lib/builtin_query_functions.ts
lib/test_deps.ts

As the user can type whatever they want as arguments, this PR changes the query functions' parameters' types to `unknown`  and adds type guards to provide better exception handling.
Here's an example, using the following snippet
````
```template
{{replace(45, "4", "5")}}
```
````
**Without type guards**
**With type guards**

Add type guards in query functions

---

common/spaces/disk_space_primitives.ts

If you have a symlink to a file (not a directory), an error is thrown:
```
Error: Not a directory (os error 20): readdir '/path/to/the/symlinked/file'
at async Object.[Symbol.asyncIterator] (ext:deno_fs/30_fs.js:220:19)
at async walkPreserveSymlinks (file:///Users/joe/projects/silverbullet/common/spaces/disk_space_primitives.ts:160:20)
at async walkPreserveSymlinks (file:///Users/joe/projects/silverbullet/common/spaces/disk_space_primitives.ts:172:7)
at async walkPreserveSymlinks (file:///Users/joe/projects/silverbullet/common/spaces/disk_space_primitives.ts:172:7)
at async DiskSpacePrimitives.fetchFileList (file:///Users/joe/projects/silverbullet/common/spaces/disk_space_primitives.ts:128:22)
at async AssetBundlePlugSpacePrimitives.fetchFileList …
```

Check if symlink is a file or directory

---

common/markdown_parser/parser.ts
web/components/page_navigator.tsx

Adjust the RegExp for matching tags in order to better support compatibility  with other PKM systems. Though not the exact matcher used in Obsidian (since  its source is closed), this matcher is modeled mostly after it and allows most  non-whitespace characters, including Emoji.
I use a task line like `- [ ] Gift Idea #🎁 #Person-Name` to denote gift ideas for friends and family. This patch allows SilverBullet to recognize the emoji.

Relax hashtag pattern matching (Support Emoji)

---

web/components/top_bar.tsx
web/styles/main.scss

Reverts silverbulletmd/silverbullet#753
I'm reverting this because of a regression in layout:

Revert "Change top bar to flexbox"

---

plugs/template/page.ts
plugs/template/template.plug.yaml

This will expose the `instantiatePageTemplate` function, so it can be used via a syscall to generate pages from space scripts . It is a small extension of #716 to make the function also available in space script.

Expose instantiate template function

---

web/cm_plugins/admonition.ts
web/styles/colors.scss
web/styles/editor.scss
web/styles/theme.scss
website/Markdown/Admonitions.md

Allows making new admonition styles and adds support for the new github style `> [!note]`
See changes to website/Markdown/Admonitions.md for instructions
#783

Custom Admonitions

---

plugs/markdown/markdown_render.ts

While using silverbullet-pub, I had issues getting images to work.  If I used absolute paths in markdown like `![](/Commands/2024-03-09_04-01-31-chat-example.gif)` it would work in SB, but the html would render as `<img src="//Commands/2024-03-09_04-01-31-chat-example.gif">` with a double slash in front, causing the image not to load.
I couldn't find anywhere else that uses `options.attachmentUrlPrefix`, so I'm assuming it was added for pub and hoping this would always be expected behavior.

Only prepend attachmentUrlPrefix if url doesnt already start with it

---

common/spaces/http_space_primitives.ts
server/http_server.ts

Fixes #615.
1. Disallow PUT on filename with filenames surrounded with spaces;
2. If the filename provided on GET is surrounded by spaces, redirect to its trimmed version;
3. In case of required authentication, return a 401 (UNAUTHORIZED) + redirect;
If you want me to create tests, I would like to know if there already exists files places I can put them in.

Fix space on end of page name creates two pages, one shadowed #615

---

plugs/index/tag_page.ts

"These are all objects..." is a bit vague in English.
We could either have "These are all *the* objects", or just "All objects..."
If the latter, a colon makes sense.

Update tag_page.ts explanation string

---

plug-api/lib/frontmatter.ts
plugs/markdown/html_render.ts

This fixes two issues I ran into.   I had several markdown files with frontmatter like this:
```markdown
---
tags:
- 2017
- conference
---
```
The `2017` tag would get parsed as a number instead of a string, so during indexing it'd throw these errors:
```
3924 An error occurred while indexing tasks: TypeError: i.replace is not a function
3925     at data:application/javascript;base64,dmFyIHhlPU9iamVjdC5k......e3luIGFzIHBsdWd9Owo=:3:772
3926     at Array.map (<anonymous>)
3927     at _ (data:application/javascript;base64,dmFyIHhlPU9iamVjdC5k......e3luIGFzIHBsdWd9Owo=:3:763)
3928     at eventLoopTick (ext:core/01_core.js:153:7)
3929     at async ie (data:application/javascript;base64,dmFyIHhlPU9iamVjdC5k......e3luIGFzIHBsdWd9Owo=:3:1416)
3930     at async …
```

Fix frontmatter indexing error when a tag is a number

---

website/Deployments/Caddy.md
website/Deployments/ngrok.md
website/Install/Deno Deploy.md
website/Install/Deno.md
website/Install/Docker.md

With the blocks consistently having the `shell` specifier, the dollar sign is not needed to indicate these lines are terminal commands. There is also no need to differentiate user `$` and root `#` shell, since the lines contain `sudo` whenever root privileges are required.
This significantly improves UX considering #735
Credit goes to Russ Williams (rlw1138) for suggesting this https://community.silverbullet.md/t/copy-to-clipboard/351
---
Since the majority of command blocks used the `shell` info string, I changed the few `bash` ones to match (as a proud `zsh` user).

Remove dollar before commands in "shell" block

---

common/space_script.ts

The Intl polyfill provided by `js-temporal` only includes the `DateTimeFormat` class. Because the global Intl is replaced with it, the other classes provided by Intl are not accessible.
I changed it, so the Intl polyfill gets applied to the global Intl, therefore only replacing the `DateTimeFormat`.

Add the Intl DateTimeFormat polyfill for space scripts without overwriting other Intl classes

---

web/cm_plugins/link.ts

Middle clicking on links just puts the cursor into the link. I set `contenteditable` to `false`, like on wiki-links to make middle click also work to open links.

Allow middle click to open link

---

web/styles/colors.scss
web/styles/theme.scss

So currently the border around panels is wrong in many cases
Especially in the `bhs` and `lhs` case
It's most noticeable in dark mode, because in white mode the border color is the same as the background (white)
This PR fixes both the position of the border and the color of the border in dark mode

Fixes panel border espacially for dark mode

---

common/settings.ts

This alters the regex for getting the settings block to not parse the content of the block greedily, because this could lead to problems where two consecutive blocks would be captured as one. [Example](https://regex101.com/r/4eekHd/1)

Fixed greedy parsing of settings block

---

common/markdown_parser/customtags.ts
common/markdown_parser/parser.ts
plugs/markdown/markdown_render.ts
web/cm_plugins/hide_mark.ts
web/style.ts
web/styles/colors.scss
website/Markdown/Extensions.md

This fixes #872
The syntax would look like this, which seems to be the one used by e.g. pandoc. The alternative would be  Github<sup>TM</sup>s `H<sub>2</sub>O`, but I think pandoc style looks neater.

Add subscript and superscript

---

plugs/markdown/preview.ts
web/components/panel.tsx
web/components/widget_sandbox_iframe.ts

So this does the same as the other PR just for the widget iframes now and I also noticed that the `panelHTML` already has an API for setting the theme of the message, so I made use of that (The widgets already do). This now allows plugs to directly to use the data-theme property for panels.

Fixes the white flash for widget iframes & Make use of panel api

---

plug-api/lib/markdown.ts
plugs/index/toc.ts

This strips the markdown in the TOC. So something like this `==FOO==` gets stripped to `FOO`. Most notably, this also strips aliased links (`[[index|Home]]` -> `Home`) and should thus fix #867.
The only problem right now is that a headline like this `# Hello ]` still results in ugly markdown for the same reasons as before and I frankly have no good ideas on how to fix this. (Btw. this whole "problem" also exists in [Obsidian](https://forum.obsidian.md/t/how-to-escape-square-bracket-in-link-custom-display-text/66826), but for them it's not that important as they don't have something like the toc plug, which programmatically renders to aliased links)
I tried to allow the escaping of the closing brackets in the regex, but this then results in issues there this `- [index| Foo \] Bar]` gets …

Strip Markdown in TOC

---

plugs/editor/clean.ts
server/http_server.ts
web/auth.html
web/service_worker.ts

Things this changes:
- This uses query parameters to redirect to the requested url after authentication. There are probably a 100 ways to implement this, hope this is ok. (Fixes #886)
- I also separated the logout into it's own route as I don't see a reason why it would be a query parameter.
- I also changed the `.all` and if else code into the proper honojs code and used a hono validator to validate the form data. in the auth route handler
- vscode also did some formatting, which changed the indenting of some blocks, which is why the diff looks kinda insane

Redirects to initial url after authentication and cleans up auth code

---

common/query_functions.ts

The mapping of the files to page names has to happen with every call to `pageExists()` as the underling array will change. Initially it's even empty and never updating it will cause the resulting mapped set to stay empty. This would mean `pageExists()` returnes `false` every time.
This issue was introduced with 1f94915 and is thus still pretty new, which is probably why it was unnoticed until now.

Fix `allKnownFiles` not being updated for `pageExists()`

---

.github/workflows/server.yml
deno.jsonc
install.sh

Since deno version 1.1.41 has been released, [ARM64 architecture for Linux is supported](https://deno.com/blog/v1.41#linux-arm64-support).
This PR proposes to support and provide a binary for this architecture.

Support arm64 arch for Linux

---

plug-api/lib/page_ref.test.ts
plug-api/lib/page_ref.ts

File extensions can contain numbers too.
My main motivation was to enable myself hosting `woff2` files right from my space, like I do for `ttf` files.
Also added some tests.

Fix up validatePageName routine

---

web/cm_plugins/fenced_code.ts
web/cm_plugins/util.ts
web/cm_plugins/wiki_link.ts
web/editor_state.ts
web/editor_ui.tsx
web/styles/colors.scss
web/styles/editor.scss

Ok, this is more of shot into the blind. It does a few things:
- It filters out all `select.pointer` events and fires an empty transaction on `mouseup`, which basically replicates obsidians behaviour for selections, meaning while you still hold down the mouse nothing happens and only when you let go, the view updates. This removes all the weird jitter/feed-back loops when selecting.
- You can now select part of a widgets code and part of the outside text and it will still render the widget code.
- Change all events for different kind of links to `click` as that is also the normal behaviour of `<a>`s. It just seems weird that sometimes stuff happens on `mouseup` and sometimes on `mousedown` (Maybe there is a reason, but I couldn't think of one). This also sometimes caused problems: When …

Change selection behaviour

---

plug-api/lib/json.test.ts
plug-api/lib/json.ts

Small follow-up commit for https://github.com/silverbulletmd/silverbullet/commit/2eb7e25854000090bdb3a8729aed3c3c1f06e381#
- removes `pad` function in favour of `String.prototype.padStart`
- adds test cases for the date formatting
Thank you @zefhemel for not only taking the time to respond but also to fix a small bug in date parsing (discussion here https://community.silverbullet.md/t/struggling-with-yaml-frontmatter-date-attribute-and-date-comparison-query-in-silverbullet/454/13)
I thought I would also thank you for putting some of my time in. Let me know if this looks OK or if you want me to make any changes.
Since this is a pure refactoring, there doesn't have to be any CHANGELOG entry 👍

Follow-up for parsing YAML dates

---

web/reducer.ts

This pull request changes `mouseDetected` to check only the primary pointing device and retains the existing logic.
I tested this change on my physical Samsung phone and a few different emulated iPhones in Firefox DevTools.
**Context**: I couldn't get the mobile-only buttons (including read-only mode) to appear in Firefox for Android, DuckDuckGo, or Samsung Internet on a Samsung Galaxy S22. `any-pointer:fine` evaluates to `true` even though I don't have a mouse connected. Based on [this article](https://www.ctrl.blog/entry/css-media-hover-samsung.html), Samsung devices might be reporting the presence of both a touchscreen and a nonexistent touchpad.
I also tried various combinations of `any-hover:hover`, `hover:hover`, `pointer:fine`, and `any-pointer:fine`.
* For some reason, `const …

Check only the primary pointing device's accuracy

---

lib/web.ts
plugs/editor/complete.ts
plugs/markdown/markdown_render.ts
type/web.ts
web/cm_plugins/markdown_widget.ts
web/cm_plugins/wiki_link.ts
web/components/page_navigator.tsx
web/components/top_bar.tsx
web/editor_ui.tsx
web/reducer.ts
web/styles/main.scss

This patch enables decorations for user specified tags - starting with handling only a single decoration - a 'prefix' to be added to the page name. Prefix is handled in the top bar title, page navigator, wiki-links appearing within a page as well as page autocomplete suggestions.

Fixes #560 and provides an initial implementation for assigning decorators to tags.

---

plugs/markdown/markdown_render.ts

Fix issue 
- https://github.com/silverbulletmd/silverbullet/issues/793
- https://github.com/silverbulletmd/silverbullet/issues/936 (closed by me because of duplication)
For the same markdown I used, it renders correctly.
```
|Header1                             |Header2                                              |
|---                                 |---                                                  |
|123                                 |456                                                  |
|123                                 |456                                                  |
```

Fix blank space above tables issue

---

plug-api/syscalls/editor.ts
plug-api/types.ts
plugs/editor/complete.ts
plugs/editor/editor.plug.yaml
plugs/editor/editor.ts
type/web.ts
web/client.ts
web/components/page_navigator.tsx
web/syscalls/editor.ts
website/All Pages Picker.md
website/Page Decorations.md
website/Page Picker.md

Originally proposed in [Soft delete notes - Ideas - SilverBullet Community](https://community.silverbullet.md/t/soft-delete-notes/674) thread.
I love how PR is documented in the `website/` every time

Add hidden pages

---

web/components/filter.tsx
website/Page Picker.md

Add another shortcut to Page Picker to make it easier to create pages in existing folders.
[Started a thread on Community](https://community.silverbullet.md/t/folder-auto-complete/686) to link for the original idea author.

Auto complete folder in Page Picker

---

type/web.ts
web/cm_plugins/smart_quotes.ts
web/editor_state.ts
website/SETTINGS.md

As discussed in [Unwanted Unicode quotation marks - Troubleshooting - SilverBullet Community](https://community.silverbullet.md/t/unwanted-unicode-quotation-marks/669)
**Needs a refresh for the setting to take effect.** I noticed that syscalls don't work in the `web` folder, so I reworked the array into function like `createCommandKeyBindings`.
I don't know nice ways to save the reference to client and check the current setting when the shortcut is triggered ¿I would use `var` to save reference to client inside the function? I don't know...
If we accept that this needs a reload, I could make it a bit simpler.

Add setting for smart quotes

---

plugs/editor/editor.plug.yaml
plugs/editor/outline.ts

I have a space script where I am using `determineItemBounds` currently, but to use it I had to copy the full function into the space script.
I'd rather expose/export it so that I don't need to duplicate that code.   I tested this and can use it like this:
```
async function refile(targetPage, targetHeading) {
try {
const cursorPos = await syscall("editor.getCursor");
const text = await syscall("editor.getText");
const currentItemBounds = await syscall("system.invokeFunction", "editor.determineItemBounds", text, cursorPos);
const currentItemText = text.slice(currentItemBounds.from, currentItemBounds.to);
...
```
Of course, let me know if there's a better way to do it

Expose determineItemBounds and ensureNewLine from editor plug

---

common/syscalls/system.ts

Related to https://github.com/justyns/silverbullet-ai/issues/47
It's pretty much a copy of system.invokeFunction, but always uses `proxySyscall`.  I'm not committed to this approach if there's a better idea

 system.invokeFunctionOnServer syscall to force proxying syscalls to server

---

web/components/panel.tsx

This was causing multiple Preact versions to be imported, creating an error when opening panels. Fixes #986.

Use aliased preact import in Panel component.

---

common/query_functions.ts
plug-api/lib/page_ref.test.ts
plug-api/lib/page_ref.ts
plug-api/syscalls/editor.ts
plugs/editor/editor.plug.yaml
plugs/editor/editor.ts
plugs/tasks/task.ts
web/client.ts
web/syscalls/editor.ts
website/CHANGELOG.md
website/Links.md
website/Plugs/Editor.md

Added new link syntax as proposed in [Community post](https://community.silverbullet.md/t/grep-plug-for-alternate-search-implementation/709/5?u=maarrk) to link to a specific line.
Also added a syscall and command with the same logic for completion.
I think since commands are run by the user from the Picker or button, I made them show where the cursor was moved

Support linking to and moving to line number in pages

---

plugs/plug-manager/plugmanager.ts
website/Plug Management.md
website/Plugs/Development.md

Summary:
- fixed the problem with `ghr` uri not ending with `.plug.js`
- the release manifest is always downloaded (instead of only doing that for latest) to give more descriptive errors
- since *every* repository in [Plugs#Third-party plugs](https://silverbullet.md/Plugs#Third-party%20plugs) is named with the `silverbullet-` prefix, this is handled and documented

Improve Plug distribution through GitHub Releases (fix #975)

---

common/spaces/http_space_primitives.ts
server/http_server.ts

related to #947 and #1012 
ping() seems to only be called once when the client first loads, this swaps /index.json for a simple static response from /.ping which shouldn't depend on disk i/o speed and pretty much always return quickly.
Kept this ping timeout at 5s, but changed the default fetch timeout for everything else from 5s to 30s.  ping timeout could probably be even lower.

Add simple /ping endpoint instead of /index.json, change default fetch timeout to 30s

---

common/spaces/disk_space_primitives.ts

Related to #947 
_(background note:  my primary sb instance is on a server with a network file system and can be kind of slow when accessing 100s or 1000s of small files)_
Basically this caches the file list in a variable.  
The cache is emptied every time a file is deleted or saved.
Every time fetchFileList is called, the cache is returned if it's less than 1 minute old.  A background sync of the cache is also triggered.  This could be on a timer instead, I'm not sure if it's needed or not?  The client triggers syncs pretty regularly, but if there are no clients connected, I'm not sure if there's a reason to constantly update the file list.
I haven't really tested this much with sync-mode and being offline for an extended period of time, but in my tests so far - /index.json is …

Add an in-memory cache of the file list for disk spaces

---

server/http_server.ts

Related to https://github.com/silverbulletmd/silverbullet/issues/1010
While testing, I noticed an invalid `indexPage` value would cause an error like this:
```
TypeError: name.startsWith is not a function
at parsePageRef (file:///Users/justyns/dev/silverbullet/query-perf/plug-api/lib/page_ref.ts:48:12)
at file:///Users/justyns/dev/silverbullet/query-perf/server/http_server.ts:250:11
at dispatch (https://deno.land/x/hono@v3.12.2/compose.ts:45:23)
at https://deno.land/x/hono@v3.12.2/compose.ts:18:12
at https://deno.land/x/hono@v3.12.2/hono-base.ts:338:31
at Hono.dispatch (https://deno.land/x/hono@v3.12.2/hono-base.ts:348:6)
at fetch (https://deno.land/x/hono@v3.12.2/hono-base.ts:361:17)
at ext:deno_http/00_serve.ts:364:24
at ext:deno_http/00_serve.ts:553:29
at eventLoopTick …
```

Fallback to index page if unable to parse the indexPage config option

---

common/syscalls/markdown.ts
plug-api/syscalls/markdown.ts

We expose `markdown.parseMarkdown` to plugs and space scripts. Why not the reverse direction, too?

Expose render parse tree to plugs/space scripts

---

web/cm_util.ts

I found some erratic behavior when using editor.setText() that seems to be caused by the underlying `diffAndPrepareChanges`. To test this, I've set up this test page content:
```
This is a page with several lines.
This is one of the lines.
This is another one of the lines.
```
And a space-script that updates it:
```
silverbullet.registerCommand({name:'Test Command'}, async() => {
await editor.setText(`I've modified this line.
This is one of the lines.
And also this line.`);
});
```
Running the command with this text results in:
```
Error running command Invalid change range 90 to 101 (in doc of length 98)
```
If I modify the new string to:
```
This is a cage with several lines.
This is one of the lines.
With another one of the lines.
```
It becomes more clear what's going on because after …

Fix diffAndPrepareChanges

---

web/client.ts
web/cm_util.ts
web/syscalls/editor.ts

Piggy-backing off of #1055, this PR uses `editor.setText()` instead of creating an entirely new `editorState` when new changes are received from the server. It's maybe not the most elegant solution but until there is a better one, this at least lets you keep typing away and keeps your cursor position when new changes are retrieved. I've also updated the editor.setText() to be an isolated transaction, this way when you lose your local changes you can undo to get them back then redo to get the server changes in.

Use setText instead of replacing entire editor state

---

plugs/markdown/preview.ts
web/styles/main.scss

This resolves https://github.com/silverbulletmd/silverbullet/issues/635, sort of...
Usually when I export a page to PDF, I print the current page. This doesn't work in Silverbullet since panels are embedded in iframes. In Firefox, using default print will only print current screen(as shown below).
This PR tries to solve this with a few lines of hacks.
However I'm not sure if this is the best way to solve the problem, so I set this PR to draft. Here are a few thoughts.
1. This PR will add a Printer button to all panels. Though it doesn't bother me , I don't think this behavior is expected by everyone. A better way could be adding a command "Markdown: Print" in markdown plug. But DOM is not accessible in web workers. Besides I need to find a way to pass around the ref to panel.
2. Another …

Export PDF through print.

---

type/config.ts
web/editor_state.ts
website/SETTINGS.md

This PR creates a `autoCloseBrackets` setting that allows to configure which brackets to automatic close (or to set it empty to disable auto-closing)

Add settings to configure auto close brackets

---

plugs/index/page_links.ts
website/YAML.md

This implements #1000
The link is indexed only if it is the full content of a string node (allowing for quotes and whitespace) to discourage writing essays in the frontmatter :smile:
I added an explanation why the quotes are needed on YAML page, I can't think of a page to document that the feature exists at all, I think it's discoverable by looking at `indexPage` in SETTINGS

Index wikilinks in frontmatter strings

---

type/client.ts
type/config.ts
web/cm_plugins/smart_quotes.ts
website/SETTINGS.md

Also deprecate `useSmartQuotes` in favour of `smartQuotes.enabled` for more logical hierarchy

Space config for smart quotes (close #1114)

---

common/markdown_parser/constants.ts
common/markdown_parser/parser.test.ts
plug-api/lib/frontmatter.ts
plug-api/lib/tags.ts
plugs/editor/navigate.ts
plugs/index/header.ts
plugs/index/paragraph.ts
plugs/index/table.ts
plugs/index/tag_page.ts
plugs/index/tags.ts
website/Markdown/Extensions.md
website/Markdown/Hashtags.md

I'd suggest to continue discussion in #1072

Parse tags starting with digits and containing spaces (close #1072)

---

web/components/panel_html.ts

This adds the possibility to set an integrity hash for the script tag that is e.g. used by the mermaid plug. If properly used, this will prevent manipulated CDN sources from being loaded into silverbullet.

Enabler to make scripts loaded from CDN more secure

---

server/crypto.ts
server/http_server.ts
web/auth.html

One source of mild frustration for me using Silverbullet is the necessity of re-logging-in every week (at least since I'm currently using basic authentication). This PR adds the ability to stay logged in, as log as the user opens Silverbullet on a given device during the one-week window.
To the `crypto.ts` file, `createJWT()` is updated to make `expirySeconds` an optional parameter, making a JWT that doesn't expire if it's not passed.
A checkbox is added to `auth.html` to the login form to mark "remember me".
In `http_server.ts`, logging in with the "remember me" checkbox checked saves an additional cookie that, if it exists, signifies the server to refresh the cookie on subsequent requests. Thus, visits to a page (given the cookies aren't expired) will move the expiration date back to a …

Create "remember me" functionality for basic auth, which sets an unexpiring jwt and refreshes the cookie during requests

---

plug-api/lib/resolve.ts

Fixes #1095 The tel URI scheme for telephone numbers not recognized in hyperlinks
This could cover all possible protocols like this:
```
return URL.parse(path)===null;
```
but that would block **lots** of page names containing a colon.

recognise tel: uri scheme as a non-local path

---

build_plugs.ts
build_web.ts

This fixes the build on windows, where `new URL("deno.json", import.meta.url).pathname` starts with `/C:/` which isn't a valid path.
First time with deno, so not sure this is idomatic.

Fix build on windows

---

web/components/top_bar.tsx
web/styles/colors.scss
web/styles/main.scss

Fixes #1129
- The progress bar now uses variable colors that align with the other nearby buttons' colors.
- The spacings in the header bar, like the Sync button when enabled, has been improved.
- The caret color being black on the note name in dark mode has been fixed.
I'm not really sure these are the correct ways to fix it since I'm not really familiar with SilverBullet's codebase,  Codemirror, Deno, etc. :sweat_smile:

Few dark mode fixes and top bar improvements

---

web/editor_state.ts

The standard keymap conflicts with the vim mode, e.g. not allowing arrow keys to move through the vim commandline for `/` and `:` commands. The keys described in
https://codemirror.net/docs/ref/#commands.standardKeymap seem to work just fine without it in vim mode.
Fixes https://github.com/silverbulletmd/silverbullet/issues/976

Do not use standardKeymap in vim mode

---

web/editor_state.ts

This is a workaround for https://github.com/replit/codemirror-vim/issues/182
Fixes https://github.com/silverbulletmd/silverbullet/pull/1145 (harder)

Fix Enter for vim mode

---

web/editor_state.ts

Accept auto-complete suggestions on tab press similar to code editors. Falls back to indent if no autocompletion context.

Allow tab press to autocomplete

---

server/http_server.ts
server/lockout.test.ts
server/lockout.ts
web/auth.html

A **very** minimal solution for #1133 Protection against brute force attacks. Lots of little decisions, so let me know if they don't suit.
This kind of thing makes it easy to DoS a server, so it defaults off.  Configured with two new environment variables:
SB_LOCKOUT_LIMIT - Maximum number of login fails before lockout
SB_LOCKOUT_TIME_MS - Time to count fails over in ms
If this is OK, where should it be documented, and should there be a command line flag for it?

Simple protection against brute force attacks

---

common/markdown_parser/parser.ts

related to issue #1160
Without this change, copy&pasting CodeSearch URLs like the following into SilverBullet breaks them: https://cs.opensource.google/go/go/+/master:src/archive/zip/reader.go;l=25;drc=9cfe3a86d34f7f4a401dae9a22389b12f7e8bb2e
I.e., they are cut off and do not link to the right target:

markdown_parser: allow comma and semicolon in naked URLs

---

web/components/panel_html.ts

Seems like for some browsers the cross origin property is case sensitive when using it in Javascript and not HTML.
This PR should fix [silverbullet/silverbullet-mermaid#5](https://github.com/silverbulletmd/silverbullet-mermaid/issues/5) and also contribute to the fix of the topic discussed [here](https://community.silverbullet.md/t/recent-problem-with-mermaid-plug/1296/5)

Fix case sensitive cross origin attribute

---

README.md

This is a follow-up to issue [#1165 ](https://github.com/silverbulletmd/silverbullet/issues/1165). The corrected link to the MIT license is in the readme.

readme MIT license link corrected

---

website/Library/Core/Snippet/yesterday.md

It's exactly like `/tomorrow` to make [Functions#Date and time](https://silverbullet.md/Functions#Date%20and%20time) are more consistent

Add Slash Command for yesterday

---

common/markdown_parser/parser.test.ts
common/markdown_parser/parser.ts

Fixes https://github.com/silverbulletmd/silverbullet/issues/1160

Fix trailing periods for naked URLs

---

plugs/editor/editor.plug.yaml
plugs/plug-manager/plugmanager.test.ts
plugs/plug-manager/plugmanager.ts

This is implementing #1042 with some minor improvements on the side.

Move Plugs to Space Config and rework "Plug: ..." commands

---

common/markdown_parser/parser.ts
plugs/markdown/markdown_render.ts
web/cm_plugins/clean.ts
web/cm_plugins/hashtag.ts
web/cm_plugins/hide_mark.ts
web/style.ts
web/styles/editor.scss
website/Objects.md
website/Space Style.md

* Wrapped the existing span for a tag with an anchor element <a> to
improve ux for screen readers (#938) 
* Added data-tag-name attribute to tags so that given a tag `#my-tag` it
will have the attribute `data-tag-name="my-tag"` added to the new `<a>`
element wrapper allowing for end users to target tags for styling with a
css selector such as `.sb-hashtag[data-tag-name="my-tag"]{...}`
* Updated docs (ie silverbullet.md docs)
Related community threads:
- https://community.silverbullet.md/t/tag-styling/1022
- https://community.silverbullet.md/t/tag-styling-improvements/1254

Update how tags are rendered to allow for custom styling 

---

server/http_server.ts

@zefhemel my Readwise plug needs to use paging in order to get all pages from Readwise.
Readwise's paging is implemented by passing a `?page=2` URL parameter, which before this PR did not make it through the proxy.
This PR reads the URL params in the proxy route and appends it to the outgoing request URL.

Fix passing URL parameters when proxying

---

web/auth.html

This adds the `for=""` attribute that allows the words "Remember me" to be clicked which will toggle the input checkbox next to it.

Allow clicking Remember me label to toggle checkbox

---

.helix/languages.toml

Similar to the `.vscode` folder tells the editor to use Deno for everything.

Add config for Helix editor

---

common/syscalls/system.ts

This also fixes a side effect where the library update status notification would never show up.

Prevent remote space script reload when syncOnly is enabled

---

web/cm_plugins/inline_content.ts

Inline content with the file containing e.g. a `:` cannot be displayed as the file name is set as the img src, and the browser treats the part before the : as the protocol, instead of as a file name.
This change encodes the file name so `:` becomes `%3A`, fixing the issue.
Fixes #1182.

Fix encoding of inline content

---

plugs/markdown/markdown_render.ts
web/cm_plugins/widget_util.ts
web/components/page_navigator.tsx

This fixes #1196
Also went through the code and looked at all instances of `replace("#`, `replace('#`, and `slice(1` to find other locations where `extractHashtag` should be used. I think now it should be good.
Also, is there a preference between imports starting with `../../plug-api` and `@silverbulletmd/silverbullet`? I see both throughout the codebase, and seems to me that Deno uses one or the other for automatic imports. I'd say that the second option is easier to copy into other files.

Correctly extract hashtag content in links and Page Picker filter

---

website/Objects.md

a small fix on the [website](https://silverbullet.md/Objects); escaping `by` in the query to prevent parsing error caused by it being a reserved keyword.

fix parsing issue caused by reserved word 'by' in query

---

website/Objects.md

Reference to page [[Space Style]] was misspelled as [[Speace Style]]

Fixed typo in page reference in docs for Objects

---

web/editor_state.ts

This fixes an issue with visual block selection in vim mode:
Current:
https://github.com/user-attachments/assets/5ed2afe2-c997-406e-b9bf-475b1b6862de
Fixed version:
https://github.com/user-attachments/assets/4e118863-2077-444c-aac5-9329c625e457
Closes #1217

fix(editor): allow multi selection while in vim mode

---

web/styles/editor.scss

When the body of a task contains a wiki style link [[]] and is checked, the link is not styled:
This uses the sort of new css `:has()` selector which is supported by most browsers: https://caniuse.com/css-has

fix: strike through links in tasks

---

plugs/markdown/markdown_render.ts

Fixes https://github.com/silverbulletmd/silverbullet/issues/1228. This matches the generated HTML to the current behavior of editor.openUrl.

Open external links in a new tab

---

plug-api/syscalls/editor.ts
web/syscalls/editor.ts

This commit exposes `client.rebuildEditorState()` function to the syscalls.

add rebuildEditorState function to the syscalls

---

common/space_lua/stdlib/os.ts
common/space_lua/stdlib/os_test.lua
website/API/os.md

Add support to format dates using the week number format specifiers:
- `%U`: US format - week 01 of the year starts on the first Sunday of the year. Days in the year prior to that week are in week 00. (00 to 53)
- `%W`: week 01 of the year starts on the first Monday of the year. Days in the year prior to that week are in week 00. (00 to 53)
- `%V`: EU / ISO 8601 format - week 01 of the year is the week containing January 4th. Days in the year prior to that week are in the last week of the year prior. (01 to 53)

Space lua: os.date add support for %U, %V and %W

---

web/cm_plugins/line_wrapper.ts
web/cm_plugins/spell_checking.ts
web/editor_state.ts

This is related to this [post](https://community.silverbullet.md/t/disable-spell-checking-in-code-blocks/1688/2). I was kinda right. It has to be set for `InlineCode` and `CodeText`, but inline code doesn't have to be less than a line and we don't want to disable spellchecking for the whole line so this has to be moved out of the the linewrapper codemirror plugin.

Fix spell checking for code blocks and inline code

---

plugs/index/toc.ts
website/Table of Contents.md

Hellow,
I'm setting up silverbullet to see if it can replace Obsidian in my life, and I needed to change what heading level the table of content header was. So, here's a PR that **is** backward compatible (since we could remove `header` and instruct to set `headerText` to `""` to achieve the same effect)
I'm not happy with the wording I came up with for the documentation, suggestions very much welcome.

Add option to personalize toc header

---

web/client.ts

When insatiating the index page through the `client.navigate` function only builtin functions were considered

---

plugs/index/toc.ts
website/Table of Contents.md

adds two new config-options to the "Table of Contents" plug:
maxLevel and minLevel.
So you are able to restrict the displayed levels to your needs.
(Second attempt for PR, this time with all tests and checks completed :-) )

added ToC min+maxLevel (second attempt, fixes #1226)

---

plugs/index/page_links.ts

Related to this [PR](https://github.com/silverbulletmd/silverbullet/pull/1066)
This PR fixes frontmatter wikilink path resolution from relative to absolute.

FIX: Frontmatter wikilinks should be resolved from root

---

deno.json
web/editor_ui.tsx
web/syscalls/editor.ts

Currently in vim mode if the editor isn't selected and I hit `j` it will cause the editor to gain focus and insert the j character before entering vim normal mode. Read only mode is broken when toggling vim mode.  This PR attempts to fix those issues.  I don't know if there's a better way to fix the read only mode than calling reloadPage but it seems to work
- remove client.focus call from global keydown handler. This call is what breaks vim mode
- add client.reloadPage call to setUiOption syscall. This appears to fix read only mode that is completely broken without the above focus call. It also seems to fix the issue when toggling vim mode
- add client.focus call to CommandPalette onTrigger if no cmd is selected. Without the client.focus call above, the editor is no longer selected when …

Vim Mode and Read Only Fixes

---

common/query_functions.ts

The check if a match was found by the heading regex was incorrect. `string.search(regex)` returns `-1` which is "truethy". 
Instead use a check if it's greater or equal than 0 (technically correct, but in practice it will even be bigger, because a next heading is at least a newline away).
Fixes #1086

fix(transclusions): don't slice if it is the last heading on the page

---

common/spaces/disk_space_primitives.ts

Using `file.write` directly once doesn't guarantee the entire file is written; see https://docs.deno.com/examples/writing_files/
Noticed this while trawling through the code working trying to reason about sync issues

Use writer to ensure the entire file is written

---

web/styles/editor.scss
web/styles/theme.scss
website/Markdown/Admonitions.md

Fixes #792 (Incorrectly formatted bold text inside a quote)
Also update the comments in the `space-style` block for the admonition documentation.
This makes it possible to copy the whole block and only change the parts that need to change.
With the old "javascript" style comments, the space-style would not load successfully.

fix(quote): prevent extra indent when first word is not an admonition

---

plugs/editor/editor.plug.yaml
type/config.ts
web/components/top_bar.tsx
web/editor_ui.tsx
web/styles/main.scss
web/styles/top.scss
website/SETTINGS.md

Fixes #1033
Adapted the [implementation](https://community.silverbullet.md/t/collapsible-vertical-action-menu-for-mobilescreens-but-not-only/1552/7) by [Mr.Red](https://community.silverbullet.md/u/Mr.Red) and [Varenia](https://community.silverbullet.md/u/s-varenia) from the SB Community.
1. The mobile menu button is added directly in the Main UI ViewComponent's actionButtons property.
2. The styling for `#sb-top` is moved to its own file, so that the media query can stay close to it. Hopefully this makes it less likely that the mobile menu is forgotten when updating the top bar styling.
3. Use CSS nesting (original implementation did not use nesting)

feat(menu): Make menu responsive

---

web/components/page_navigator.tsx
web/fuse_search.ts

This fixes a bug where page attributes could overwrite internal variables leading to unwanted behaviour
https://community.silverbullet.md/t/page-picker-always-opens-a-new-browser-tab-when-selecting-certain-pages-like-person-joe/1997
(Someday this should be properly typed)

Don't spread page meta in page navigator

---

server/http_server.ts

see [commit message](https://github.com/silverbulletmd/silverbullet/commit/0b8cdd17aabef256117eee0dd29e7028d1d21681)
```
Content-Type header in HTTP custom endpoint response handlers are now respected
Before the commit, adding a Content-Type header in the reponse from the handler of a http:request:foobar event would be ignored and set to text/plain because of using ctx.text to return the request. ctx.text will set Content-Type to text/plain.
Now, if a Content-Type header is detected it will use a plain ctx.body response which does not alter Content-Type.
```

Content-Type header in HTTP custom endpoint response handlers are now respected

---

web/editor_ui.tsx
web/styles/top.scss

The expander button was only shown on mobile devices (if no mouse is detected), but the menu is a responsive menu.
Therefore on desktop, it hid the sync button instead.
1. By adding a class to the button, we can hide it explicitly, reducing the chances of hiding the wrong button.
2. Remove the check on `viewState.isMobile` to also show the button on desktop (under 600px wide).
Thanks to @MrMugame for the bug report.

fix(menu): only hide expander button and show button on (small) desktop

---

plugs/core/Library/Std/Table.md

Aligns column separators as proposed to close #12.
Preserves alignment specifiers and takes them into consideration for column width (see also #847, #1293)

Implement table formatting in Space Lua (close #12)

---

plugs/index/table.test.ts
plugs/index/table.ts

The missing cells are undefined, just like in the past for shorter rows. Refactored the indexing function a bit to make it easier to test, and added unit tests. Changed local imports to import map where applicable.

Fix indexing of missing table cells (fix #1104)

---

web/components/top_bar.tsx
web/styles/top.scss

Move the sync progress wrapper outside of the container that holds the menu icons.
This way, sync progress is always visible, even on smaller screens where the menu might be hidden or moved.
Hamburger menu:
Bottom bar:

fix(menu): Move sync progress wrapper outside of actions menu

---

web/document_editor_skeleton.ts

This is should be the default behaviour as silverbullet keybinds should always have priority over keybinds implemented by document editors.
*(When properly developing more complex things one notices a few things)*

[Change]: Catch event in capturing phase instead of bubbling phase inside document editors

---

web/syscalls/fetch.ts

Doing http requests to application/xml returns integer array instead of text. This would return text we can parse. issue (#1319)

Add support for application/xml content type in lua http.request

---

Library/Std/Tag.md

Paragraphs were not included in the queries of the tag page.
Second attempt, as previous PR got closed by moving v2 to main.

Added paragraphs to tag-page

---

Library/Std/Tag.md

Query results are not ordered nicely (IMHO).
So I added "order by ref" to each query.
Second attempt, as previous PR got closed by moving v2 to main.

tag-page: changed order of queries

---

common/PAGE_TEMPLATES.ts

Per https://community.silverbullet.md/t/query-ordered-by-lastmodified-does-not-work-as-expected-with-the-example/2252

Add `desc` to query example to work as described

---

website/API/editor.md

This fixes #1344
Also added description field from FilterOption, others didn't seem relevant.

Fix table constructor in editor.filterBox example

---

Library/Std/Pages/Maintenance.md
Library/Std/Template.md
website/API/template.md

When omitted, the function outputs empty string for empty table as before. The feature was motivated by the Maintenance page in v1 that showed messages instead of just empty blocks (ported over).
I tried to get this working without touching the stdlib, but since I can't define variables in `${ }` blocks I didn't manage to do it.

Add optional argument to template.each for empty collection output

---

Library/Std/Config.md
plug-api/syscalls/editor.ts
plugs/editor/editor.plug.yaml
plugs/editor/vim.ts
type/client.ts
web/syscalls/editor.ts
website/Vim.md

Alright, hear me out here.
I know what you are thinking; why do it via the CONFIG file when it can be done via VIMRC?
Well, the new Lua implementation is great, and I like customising SB with custom commands.
If I want to invoke these, I could use shortcuts, but then I'm limited to only some key bindings. I prefer custom vim keybindings.
To my knowledge, there is no way to map Vim keybindings to SilverBullet commands. (otherwise, this pull request is pointless)
So, this commit allows you to define a custom _ex_ command that invokes a SilverBullet command, which you can then map to a custom vim keybind.
Since the [CodeMirror Vim Mode API](https://codemirror.net/5/doc/manual.html#vimapi) also allows you to `map`, `unmap` and `noremap`, I've implemented these as well.
The CodeMirror API has …

feat: configure vim in CONFIG

---

server/space_server.ts

This pull request ensures that the correct name for the index page is used during server initialization. This is relevant only when the default name is overridden using the `SB_INDEX_PAGE` environment variable. In such cases, we should create `<SB_INDEX_PAGE>.md` instead of `index.md`, using the default template content.

Fix index page naming during server initialization

---

web/syscalls/shell.ts

In the current implementation, an exception is thrown when a shell command exits with a non-zero code. While there may have been a good reason for this behavior, in my use case, non-zero exit codes are expected and should not result in an exception.
This pull request proposes removing the exception and returning the `code`, `stdout`, and `stderr` as-is. If there was a specific scenario this was meant to safeguard, I’m happy to adapt the pull request - but in that case, I’d need more context on what it’s protecting against.

Allow non-zero shell exit codes

---

.gitignore
build_bundle.ts
build_plugs.ts
build_web.ts
update_version.ts
version.ts

Generate version from git describe at build time using:
```bash
git describe --tags --long --dirty
```
This makes it easy to identify the exact version a particular instance is running.
Calling `${system.getVersion()}` now returns a string like `"2.0-beta (0.10.4-209-gcdbee2fa)"`.

Generate version from git describe at build time

---

common/PAGE_TEMPLATES.ts
plug-api/lib/resolve.test.ts
plugs/federation/util.test.ts
web/syscalls/fetch.ts
website/Federation.md
website/Libraries.md
website/Library/Core.md
website/Library/Core/Page/Space Overview.md
website/Library/Core/Page/Template Index.md
website/Library/Journal.md
website/Live Template Widgets.md
website/SETTINGS.md
website/Space Config.md

Fixes #1381 
Change domain to v1.silverbullet.md
After the domain migration, some users[^1] who still use the old version complains about their installation being broken or incomplete.
This commit changes the domain to point to v1.silverbullet.md for v1 users
[^1]: Users for the Yunohost package [reporter on the Forum](https://community.silverbullet.md/t/silverbullet-packaged-for-yunohost-to-easily-self-host-it/313/14?u=fflorent) and [on Github](https://github.com/YunoHost-Apps/silverbullet_ynh/issues/33).

Fix domain v1

---

.github/workflows/docker.yml

I read on https://community.silverbullet.md/t/docker-image-included-software/1931/24 that build times were a concern, so I thought it would be worth taking a look at this.
The docker build should be pretty quick locally due to the layers being cached between builds, I imagine that for most builds the only changes should be when Silverbullet code changes and that's on the final layers. So the issue must be on GitHub Actions.
I added GitHub Actions Cache to the build and got these numbers
- control build: 9m 22s
- build with cache, first run: 11m 22s
- build with cache, second run: 1m 12s
Note that on my tests I removed these steps:
- "Login to Docker Hub"
- "Log in to the ghcr Container registry"
- "Extract metadata (tags, labels) for Docker"
There seems to be different strategies to …

Add GitHub Actions Cache to reduce build times

---

Library/Std/Config.md
common/space_lua/query_collection.test.ts
common/space_lua/query_collection.ts
type/client.ts
website/CONFIG.md
website/Space Lua/Lua Integrated Query.md

Configurable with queryCollation, default value maintains old behaviour. Added schema, example settings, and documentation to query page.
Close: #614
Close: #1316

Order strings in queries using collation algorithm

---

Library/Std/Pages/Maintenance.md
Library/Std/Template.md
common/space_lua/lua.test.ts
common/space_lua/stdlib.ts
common/space_lua/stdlib/global_test.lua
website/API/global.md
website/API/template.md
website/Space Lua.md
website/Space Lua/Lua Integrated Query.md

More general implementation of #1359
This also documents current workaround for #1343

Utility function to handle empty query results and templates

---

lib/plugos/syscalls/event.ts
plug-api/syscalls/event.ts

The documentation, example, and other function names use `listEvents`, but `event.list` is being registered with the client.

Update registered syscall for event.listEvents

---

web/styles/editor.scss

- Increase the left, right, and top margins from -15px to -10px to match the container's padding.
- Add a 10px margin below the header to create consistent margin around the contents.
- Reduce horizontal padding to 10px.
- Increase bottom padding to 15px to match the top.

Update widget header to not overflow container

---

web/cm_plugins/admonition.ts
web/styles/theme.scss
website/Markdown/Admonitions.md

Fixes: #1402 
I don't really think it's a true valid issue since it can easily be overwritten using a custom `space-style` that is case-sensitive. But I can understand it can be a bit confusing since the docs point to a GitHub discussion that uses capitalization.
The CSS attribute is now explicitly set to be case-insensitive (this is also reflected in the updated docs), and the admonition attribute name has been standardized to lowercase to ensure the correct icon appears.
It's true that we lose case sensitivity here, but I don’t see a compelling reason for users to define multiple admonitions with the same name but different capitalizations.

fix: case insensitive admonitions by default

---

plug-api/lib/json.ts

For negative time zone offsets, object attribute dates were returning the day before the desired result.
See https://community.silverbullet.md/t/date-manipulation-problems/2389

Use UTC year, month, and date for strings lacking time components

---

server/space_server.ts

In this commit, the server checks for a `CONFIG.md` file in the entire file list, rather than only in the root directory.
Having this file in the root directory might be helpful for new users, as it provides a starter template at an easy to find location. However, if the file is moved to a custom location, the original template gets recreated after a server restart.
There's even a case to be made that this config file may not be necessary at all, since all `space-lua` code blocks are already evaluated.
Alternatively, this behaviour could be controlled via an environment variable, similar to how `SB_INDEX_PAGE` is handled, but I'm not sure what's preferred.

feat: allow CONFIG.md in any directory

---

build_bundle.ts

Silverbullet currently tries to download dependencies at runtime. I'm not sure what the intended reason is, but when deploying in immutable containers or on NixOS, this becomes a problem. I'm not experienced with deno so please let me know if I'm missing anything. If at all possible, it would be nice to see a minor version bump with pre-built files having this fix.

fix: bundle external dependencies

---

Library/Std/Widgets.md
web/styles/editor.scss

Hello, this PR updates the styling of the mentions widget.
*Rationale:* Better separation of mentions and headings are easier to skim over.
**After**
**Before**

upd: Improved Mention UI

---

web/editor_ui.tsx
web/styles/colors.scss
web/styles/main.scss

Modals had a background and border before, which made it hard to e.g. achieve rounded edges. I see no reason for this. If a modal should have a border/background the developer should add them themselves.
Also the check for rendering panels didn't allow for a `mode` of `0`, which was kind of weird imo. Took me a second to find that.

Improvements for Modals

---

plugs/index/snippet_extractor.test.ts
plugs/index/snippet_extractor.ts

Hello, this PR extends the number of lines shown in the references/mentions of a given page. It attempts to keep the page name centered with content left/right to it, while not including subsequent blocks.
_Rationale:_ With the current single line it becomes difficult to see in which context a page has been mentioned.
_Note:_ The existing algorithm is kept to cover for edge cases (e.g. very short references).

upd: extend mentions for additional context

---

plug-api/syscalls/markdown.ts
web/syscalls/markdown.ts

Hello, `markdownToHtml()` exists in Lua but is not exposed as a syscall for TypeScript plugins (stumbled over it [here](https://silverbullet.md/Library/Std/Export)).
This PR:
1. Adds `markdown.markdownToHtml` syscall in `web/syscalls/markdown.ts` which converts a markdown string to HTML
2. Adds the corresponding TypeScript API function in `plug-api/syscalls/markdown.ts`
This ensures API parity between Lua and TypeScript environments, allowing plugins to render markdown
content to HTML as documented.
Do let me know if it is not expected to be exposed!

fix: expose markdownToHtml

---

plugs/tasks/task.ts

Hello, this PR updates the task cycle command (`Alt+t`) to support an additional state of “no task”, and allows toggling also if the cursor is at the beginning of a line.
Example:
```
- Some test
// Alt+t
// Alt+t
// Alt+t
- Some test
```
```
1. Some test
// Alt+t
1. [ ] Some test
// Alt+t
1. [x] Some test
// Alt+t
1. Some test
```

upd: task cycle state to remove task

---

Library/Std/Widgets.md

Added sorting for page name to the query of "Linked Tasks", just like it is with "Linked Mentions".

Add sorting to "Linked Tasks widget"

---

web/components/filter.tsx

This fixed #1454 and [this post](https://community.silverbullet.md/t/page-picker-scrolls-to-selection-every-time-sync-occurs/2035/3)
I opted for the else if here, because the switch was just getting confusing if i didn't instantly return and we already had doubling cases.

Only `scrollIntoView` when selection changes

---

web/cm_plugins/wiki_link.ts
web/markdown_parser/constants.ts

Issues this fixes or where it takes a first step to fixing it:
- https://community.silverbullet.md/t/silverbullet-render-failed-when-ref-to-a-header-with-links-inside/858 (Fixed)
- #1462 (Fixed)
- https://community.silverbullet.md/t/is-there-a-markdown-api-function-to-convert-md-to-raw-text-only/2616 (Fixed)
- #867 (Regression, was fixed by #887, partially fixed now)
All those issues were related to wiki links not properly parsing, because they contained stuff like links in the alias or header. I fixed the issue by lazily parsing anything inside a wiki link. This now makes wiki links one of things with the highest priorities, which seems sensible in my opinion. This now also allows stuff like `[[|]]` to exist, which can be helpful when generating wikilinks from spacelua for example. (This …

Parse wiki links more freely

---

type/client.ts
web/client.ts
web/cm_plugins/iframe_widget.ts
web/cm_plugins/lua_widget.ts
web/components/widget_sandbox_iframe.ts

This adds a copy button to the button bar of lua block widgets. It copies the content of the widget to the clipboard. For markdown widgets the content is the trimmed markdown content, for html widgets the content is the html.
The second commit is only half related and cleans up some code, I can revert it if you want. It just removes some doubled types and unused properties.
(Btw: What really speaks against dropping codeWidgets :eyes: ?)

Add a copy button

---

web/cm_plugins/lua_widget.ts
web/cm_plugins/top_bottom_panels.ts
web/hooks/event.ts
web/styles/editor.scss

This basically is my answer to #1474, it implements an `ArrayWidget` which just takes a callback for an array of widget content and renders the individual widgets. This class is used to render multiple top and or bottom widgets. Arguably this could be considered hacky, but the implementation really isn't that bad and decently small. The only real thing to consider is that it taps into the widgetCache and activeWidgets set, which was previously only used by lua widgets, but this shouldn't matter.
Another thing is, to return event results in order (the order the event handlers are traversed), this change shouldn't break anything for users (otherwise they are dependent on a race condition), but allows the user to use the typically lua priority to order the top or bottom widgets.
~~I also …

Allow multiple panel widgets

---

web/components/basic_modals.tsx
web/components/filter.tsx
web/components/mini_editor.tsx
web/components/top_bar.tsx

It was possible to edit the page name on the official homepage.  
I fixed it by adding a new attribute to the MiniEditor

Fixed editable page title in readonly-mode

---

web/syscalls/editor.ts

With the old syntax the user could omit the `kind = "page"`, which was not accounted for with the new legacy support.

Fix the legacy support in `editor.navigate`

---

web/document_editor.ts

Removes the sandbox attribute from document editors. This has two advantages
- I ran into a situation where I needed popus. I thought it was reasonable to not allow specific stuff, but I think it's more annoying than useful
- Removes the warning in the console

Follow up to #1526

---

client/space_lua/arithmetic_test.lua
client/space_lua/ast.ts
client/space_lua/eval.ts
client/space_lua/lua.test.ts
client/space_lua/parse.ts

This patch fixes the Lua arithmetic model at parser level only. Runtime level fixtures are left for future work.
MOTIVATION
Space Lua treats all numbers as IEEE-754 doubles (JS semantics), so it preserves negative zero. Lua uses integers and floats. The literal "-0" in Lua is parsed as unary minus applied to the integer literal "0", which yields the integer "0" (no sign). This difference flips the sign of the divisor in "1/-0" and "-1/-0". Although it could be fixed without touching the parser by changing only unary minus evaluation, this commit goes a little further and provides integer vs float differenciating at the parser level as well and uses it to fix the unary minus evaluation.
Extensive tests are added to test this exact change works and the Space Lua arithmetic model is aligned …

Fix Lua arithmetic model (parser level only)

---

libraries/Library/Std/Widgets/Widgets.md

When item itself is a link, it seems to be rendered as `[[[[header_name]]]]`
Just stripping `[[ ]]` from the title before creating anchor link.
Before:
After:

silverbullet: fix ToC rendering when item itself is a link.
